# Generated by Django 5.0 on 2023-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotifytoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
