# Generated by Django 5.0 on 2023-12-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='code',
        ),
    ]
